### ISSUE TITLE
Bug: 500 error when bedevere received "commit.pushed" webhook events.

### ISSUE THREAD

**Issue by Mariatta** [python/bedevere#582]
I'm seeing several errors in the webhook deliveries.

Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906290794550&selected=1636847906290794550) [heroku/router](https://my.papertrailapp.com/events?q=program%3Aheroku%2Frouter&focus=1636847906290794550&selected=1636847906290794550) at=info method=POST path="/" host=bedevere.herokuapp.com request_id=[e201214d-1c1d-44fa-8ec6-38a3d34a1d09](https://my.papertrailapp.com/systems/bedevere/events?q=%22e201214d-1c1d-44fa-8ec6-38a3d34a1d09%22&focus=1636847906290794550&selected=1636847906290794550) fwd="[140.82.115.81](https://my.papertrailapp.com/systems/bedevere/events?q=%22140.82.115.81%22&focus=1636847906290794550&selected=1636847906290794550)" dyno=web.1 connect=0ms service=1349ms status=500 bytes=188 protocol=https
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744386&selected=1636847906697744386) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744386&selected=1636847906697744386) Traceback (most recent call last):
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744387&selected=1636847906697744387) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744387&selected=1636847906697744387)   File "/app/bedevere/__main__.py", line 40, in main
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744388&selected=1636847906697744388) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744388&selected=1636847906697744388)     await router.dispatch(event, gh, session=session)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744389&selected=1636847906697744389) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744389&selected=1636847906697744389)   File "/app/.heroku/python/lib/python3.10/site-packages/gidgethub/routing.py", line 89, in dispatch
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744390&selected=1636847906697744390) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744390&selected=1636847906697744390)     await callback(event, *args, **kwargs)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744391&selected=1636847906697744391) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744391&selected=1636847906697744391)   File "/app/bedevere/stage.py", line 154, in new_commit_pushed
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744392&selected=1636847906697744392) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744392&selected=1636847906697744392)     await request_core_review(
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744393&selected=1636847906697744393) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744393&selected=1636847906697744393)   File "/app/bedevere/stage.py", line 272, in request_core_review
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744394&selected=1636847906697744394) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744394&selected=1636847906697744394)     await stage(gh, issue, blocker)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744395&selected=1636847906697744395) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744395&selected=1636847906697744395)   File "/app/bedevere/stage.py", line 99, in stage
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744396&selected=1636847906697744396) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744396&selected=1636847906697744396)     await _remove_stage_labels(gh, issue)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744397&selected=1636847906697744397) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744397&selected=1636847906697744397)   File "/app/bedevere/stage.py", line 91, in _remove_stage_labels
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744398&selected=1636847906697744398) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744398&selected=1636847906697744398)     await gh.delete(issue["labels_url"], {"name": stale_name})
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744399&selected=1636847906697744399) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744399&selected=1636847906697744399)   File "/app/.heroku/python/lib/python3.10/site-packages/gidgethub/abc.py", line 295, in delete
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744400&selected=1636847906697744400) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744400&selected=1636847906697744400)     await self._make_request(
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744401&selected=1636847906697744401) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744401&selected=1636847906697744401)   File "/app/.heroku/python/lib/python3.10/site-packages/gidgethub/abc.py", line 121, in _make_request
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744402&selected=1636847906697744402) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744402&selected=1636847906697744402)     data, self.rate_limit, more = sansio.decipher_response(*response)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744403&selected=1636847906697744403) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744403&selected=1636847906697744403)   File "/app/.heroku/python/lib/python3.10/site-packages/gidgethub/sansio.py", line 378, in decipher_response
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744404&selected=1636847906697744404) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744404&selected=1636847906697744404)     raise exc_type(*args)
Sep 08 09:56:14 [bedevere](https://my.papertrailapp.com/systems/bedevere/events?focus=1636847906697744405&selected=1636847906697744405) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1636847906697744405&selected=1636847906697744405) gidgethub.BadRequest: Label does not exist

**Comment by Mariatta** [comment]
This could be related to the issue where `awaiting core review` label were added after merging. Example https://github.com/python/cpython/pull/109082

I'm looking into this.

**Comment by AA-Turner** [comment]
Stale/resolved, closing
